### ISSUE TITLE
Strict HTTParty version

### ISSUE THREAD

**Issue by kimenye** [AfricasTalkingLtd/africastalking-ruby#6]
The gem currently has a hard HTTParty version of `0.16.4` in the gemspec which limits its use in other projects that might be using a higher version. Suggest making the version `~> 0.16.4`

**Comment by itzbernoulli** [comment]
I see nothing has been done with regards to this issue. Is there any reason why this issue has not been attended to by the maintainer or has there been any pull requests to address this?

**Comment by jwoudenberg** [comment]
Big thank you to the maintainers of this Gem for all their work on it!

We'd also love an update to a newer version of `httparty`, considering we've seen a reported vulnerability for the version currently pinned:
https://security.snyk.io/vuln/SNYK-RUBY-HTTPARTY-3188560

**Comment by tomshy** [comment]
There's a [PR](https://github.com/AfricasTalkingLtd/africastalking-ruby/pull/44) raised to address this

**Comment by gutschi** [comment]
Please handle the security fix, thanks. Is this project actively maintained?

We cannot use the gem due to this, excerpt below, as other authors above already stated ...

Name: httparty
Version: 0.16.1
GHSA: GHSA-5pq7-52mg-hr42
Criticality: Medium
URL: https://github.com/jnunemaker/httparty/security/advisories/GHSA-5pq7-52mg-hr42
Title: httparty has multipart/form-data request tampering vulnerability
Solution: upgrade to '>= 0.21.0'

**Comment by loisek** [comment]
@gutschi Yes, this project is actively maintained.

@tomshy @kimenye @jwoudenberg @itzbernoulli @gutschi, we are sorry that you could not use the gem.
We will sort out this issue.

Thank you for your patience.

**Comment by loisek** [comment]
The dependencies have been updated to the latest versions.
Thank you for raising these issues.
Happy hacking!
